# For docker usage: leave it here
# For non-docker usage: copy it to $HOME/.pimpmyvocab
log:
  level:          # optional (default: debug)
  file:           # optional (for docker: /pimpmyvocab/logs/bot.log)
db:
  url:            # required (example: postgresql://user:pass@host:port/db_name)
  migration-path: # required (for docker: /pimpmyvocab/db/migration)
bot:
  use-proxy:      # optional (true/false; default: false)
  proxy-url:      # required if use-proxy == true
  token:          # required
dictionary:
  token:          # required (yandex.Dictionary token)